# commit to be tagged for new release
commit = "HEAD"

project_name = "Talos"
github_repo = "siderolabs/talos"
match_deps = "^github.com/((talos-systems|siderolabs)/[a-zA-Z0-9-]+)$"

# previous release
previous = "v1.7.0"

pre_release = true

preface = """\
"""

[notes]
    [notes.updates]
        title = "Component Updates"
        description = """\
Kubernetes: 1.30.1
Linux: 6.6.30
containerd: 1.7.16

Talos is built with Go 1.22.3.
"""


    [notes.zstd]
        title = "ZSTD Compression"
        description = """\
Talos Linux now compresses kernel and initramfs using ZSTD.
Linux arm64 kernel is now compressed (previously it was uncompressed).
"""

[make_deps]

    [make_deps.tools]
        variable = "TOOLS"
        repository = "github.com/siderolabs/tools"

    [make_deps.pkgs]
        variable = "PKGS"
        repository = "github.com/siderolabs/pkgs"

    [make_deps.extras]
        variable = "EXTRAS"
        repository = "github.com/siderolabs/extras"
